version '3.5'

networks:
 localdev:
    name: localdev

services:
    main-api:
        build: BackEnd/
        restart: : always
        ports:
            - "7000:80"
        depends_on:
            - db-server
        networks:
            - localdev
        
    db-server:
        image: postgres
        container_name: db-server
        environment: 
            POSTGRES_PASSWORD: 'admin'
        ports: 
            - "1400:1433"
        networks:
            - localdev

